USE DATABASE CUSTOMER360_DEV;
USE SCHEMA RAW;

-- RAW CUSTOMERS
CREATE OR REPLACE TABLE RAW_CUSTOMERS (
    CUSTOMER_ID      INT,
    FIRST_NAME       STRING,
    LAST_NAME        STRING,
    EMAIL            STRING,
    SIGNUP_DATE      TIMESTAMP_NTZ,
    COUNTRY          STRING,
    CITY             STRING,
    STATUS           STRING,
    UPDATED_AT       TIMESTAMP_NTZ
);

-- RAW PRODUCTS
CREATE OR REPLACE TABLE RAW_PRODUCTS (
    PRODUCT_ID       INT,
    PRODUCT_NAME     STRING,
    CATEGORY         STRING,
    PRICE            NUMBER(10,2),
    CURRENCY         STRING,
    UPDATED_AT       TIMESTAMP_NTZ
);

-- RAW ORDERS
CREATE OR REPLACE TABLE RAW_ORDERS (
    ORDER_ID         INT,
    CUSTOMER_ID      INT,
    ORDER_DATE       TIMESTAMP_NTZ,
    ORDER_STATUS     STRING,
    TOTAL_AMOUNT     NUMBER(10,2),
    CURRENCY         STRING,
    UPDATED_AT       TIMESTAMP_NTZ
);

-- RAW ORDER ITEMS
CREATE OR REPLACE TABLE RAW_ORDER_ITEMS (
    ORDER_ITEM_ID    INT,
    ORDER_ID         INT,
    PRODUCT_ID       INT,
    QUANTITY         INT,
    UNIT_PRICE       NUMBER(10,2),
    CURRENCY         STRING,
    UPDATED_AT       TIMESTAMP_NTZ
);
