USE DATABASE CUSTOMER360_DEV;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE ETL_WATERMARK (
    TABLE_NAME      STRING NOT NULL,
    LAST_LOADED_AT  TIMESTAMP_NTZ,
    CONSTRAINT PK_ETL_WATERMARK PRIMARY KEY (TABLE_NAME)
);
